### ISSUE TITLE
Favor Item and/or Block Tags

### ISSUE THREAD

**Issue by MacaylaMarvelous81** [ModsByLeo/DontDropIt#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Related problem

Currently, you can favor items by Item ID, Enchantment ID, and Item Tag ID. To favor items like shulker boxes which have many variations, and only those (not all items with an inventory), you will have to favor all item id. So you should be able to favor Item ID (like #minecraft:fish for all fish) and/or Block ID (like #minecraft:shulker_boxes) to favor all items with that tag.

### Suggested solution

Enable usage of tags in Item ID section

### Alternative solutions

Add a tags section in favorites section of mod configuration which favors all items with the listed tags.

**Comment by Leo40Git** [comment]
You just stated that there's a way to add favorites via (item) tags! Just add the identifier of that tag to the item tags list on the favorites tab, no `#` prefix.

As for block tags, most block tags have an equivalent item tag that's identical (just selects the block items rather than the block itself), so I consider adding support for block tags specifically not worth it.
